### ISSUE TITLE
Save output as a file or variable

### ISSUE THREAD

**Issue by ghost** [Tufin/oasdiff-action#4]
This GitHub action is really great, however, I would like to get the result and send it to any messaging channel (MS Teams). However, now it is not possible, since GitHub does not support getting stdout from the previous step. Do you have any idea how to achieve this?

**Comment by effoeffi** [comment]
Hello @martinformi 
Did you try [Setting an output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)?
